### ISSUE TITLE
Vision.ClientException when running for the first time

### ISSUE THREAD

**Issue by PierrickI3** [Microsoft/AzureSearch_JFK_Files#1]
Hi,

when running for the first time after creating the services on Azure, I get the following exception. Since it does not really say much, could you help me troubleshoot it?

```
Initializing Services
Creating Synonym Map
Create the index
Boosting Documents
Sending a test image through the pipeline
01/25/2018 08:26:52 Info Processing blob:photo_jpg
Processing resized-image
Processing ocr-result
An Error has occured: System.AggregateException: One or more errors occurred. ---> Microsoft.ProjectOxford.Vision.ClientException: Exception of type 'Microsoft.ProjectOxford.Vision.ClientException' was thrown.
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.HandleException(Exception exception)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>b__39_1[TRequest,TResponse](Exception e)
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>d__39`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<RecognizeTextAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.Vision.<GetText>d__6.MoveNext() in E:\Boulot\Genesys\Cloud Architects\Gennovation\AzureSearch_JFK_Files\Microsoft.Cognitive.Skills\Vision.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.SkillSet`1.<>c__DisplayClass12_0`2.<<AddSkill>b__0>d.MoveNext() in E:\Boulot\Genesys\Cloud Architects\Gennovation\AzureSearch_JFK_Files\Microsoft.Cognitive.Skills\SkillSet.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.Skill`1.<GetAsync>d__6.MoveNext() in E:\Boulot\Genesys\Cloud Architects\Gennovation\AzureSearch_JFK_Files\Microsoft.Cognitive.Skills\Skill.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Cognitive.Skills.SkillSet`1.<ApplyAsync>d__5.MoveNext() in E:\Boulot\Genesys\Cloud Architects\Gennovation\AzureSearch_JFK_Files\Microsoft.Cognitive.Skills\SkillSet.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EnricherFunction.EnrichFunction.<Run>d__12.MoveNext() in E:\Boulot\Genesys\Cloud Architects\Gennovation\AzureSearch_JFK_Files\EnricherFunction\EnrichFunction.cs:line 172
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at DataEnricher.Program.InitializeServices() in E:\Boulot\Genesys\Cloud Architects\Gennovation\AzureSearch_JFK_Files\DataEnricher\Program.cs:line 158
   at DataEnricher.Program.Main(String[] args) in E:\Boulot\Genesys\Cloud Architects\Gennovation\AzureSearch_JFK_Files\DataEnricher\Program.cs:line 30
---> (Inner Exception #0) Microsoft.ProjectOxford.Vision.ClientException: Exception of type 'Microsoft.ProjectOxford.Vision.ClientException' was thrown.
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.HandleException(Exception exception)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>b__39_1[TRequest,TResponse](Exception e)
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>d__39`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<RecognizeTextAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.Vision.<GetText>d__6.MoveNext() in E:\Boulot\Genesys\Cloud Architects\Gennovation\AzureSearch_JFK_Files\Microsoft.Cognitive.Skills\Vision.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.SkillSet`1.<>c__DisplayClass12_0`2.<<AddSkill>b__0>d.MoveNext() in E:\Boulot\Genesys\Cloud Architects\Gennovation\AzureSearch_JFK_Files\Microsoft.Cognitive.Skills\SkillSet.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.Skill`1.<GetAsync>d__6.MoveNext() in E:\Boulot\Genesys\Cloud Architects\Gennovation\AzureSearch_JFK_Files\Microsoft.Cognitive.Skills\Skill.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Cognitive.Skills.SkillSet`1.<ApplyAsync>d__5.MoveNext() in E:\Boulot\Genesys\Cloud Architects\Gennovation\AzureSearch_JFK_Files\Microsoft.Cognitive.Skills\SkillSet.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EnricherFunction.EnrichFunction.<Run>d__12.MoveNext() in E:\Boulot\Genesys\Cloud Architects\Gennovation\AzureSearch_JFK_Files\EnricherFunction\EnrichFunction.cs:line 172<---
```

**Comment by awaemmanuel** [comment]
@PierrickI3 I had this error before. I solved it by making sure that the **Computer Vision API** (and any other cognitive service api you call) is deployed in **westus**, it seems like all the cognitive services default there and unless you have a way to update the service host of your request, then it will keep hitting this error.

**Comment by CoromT** [comment]
Unfortunately, the ClientException thrown by the Vision API doesn't indicate what the error is.  This failure is occurring sending the test image through the pipeline, so the problem is most likely with either the API key being used or the endpoint.  As Emmanuel pointed out the API will default to the westus region endpoint.

I'll update the code so that this is in the configuration if you want to change it.  In the meantime you can change this by  changing line 23 of Microsoft.Cognitive.Skills\Vision.cs from:
    visionClient = new VisionServiceClient(visionApiKey);
to:
  visionClient = new VisionServiceClient(visionApiKey, "northeurope.api.cognitive.microsoft.com");
where "northeurope.api.cognitive.microsoft.com" is the region you deployed the vision service to that are listed here:
https://westus.dev.cognitive.microsoft.com/docs/services/56f91f2d778daf23d8ec6739/operations/56f91f2e778daf14a499e1fa

**Comment by PierrickI3** [comment]
Thanks @CoromT! My Azure trial has expired so I will test this when I can get a new one

**Comment by CoromT** [comment]
Keep in mind that the Free tier of the cognitive services Vision API is rate limited to something like 5 documents per minute, and we make a call to the vision service for each page in the PDF.  It's easy to hit this and the code currently does not wait and retry when it does, so consider using the first paid tier, or add some retry logic.

**Comment by torokzs** [comment]
In Vision.cs line 23 the following modification helped me:

visionClient = new VisionServiceClient(visionApiKey, "https://westcentralus.api.cognitive.microsoft.com/vision/v1.0"); 

Uri should be modified in line 142 as well:

var uri = "https://westcentralus.api.cognitive.microsoft.com/vision/v1.0/recognizeText?handwriting=true";

**Comment by CoromT** [comment]
I've just pushed an update that fixes this.  You can now just specify the region for the vision service in the config.
