### ISSUE TITLE
npm run build:prod fails with error 

### ISSUE THREAD

**Issue by DavideDelVecchio** [Microsoft/AzureSearch_JFK_Files#33]
When running  npm run build:prod as from installation details, it fails with error on the  `npm run clean && env-cmd .env cross-env NODE_ENV=production webpack -p --config=webpack.prod.config.js`  platform is 

node v8.9.0
npm  v5.6.0

Stack trace
 at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at maybeClose (internal/child_process.js:925:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by briansmi** [comment]
Hi Davide, npm build should be fixed now with the latest change.  Thanks for opening the issue.
