### ISSUE TITLE
Microsoft.ProjectOxford.Vision.ClientException 

### ISSUE THREAD

**Issue by MercyPrasanna** [Microsoft/AzureSearch_JFK_Files#4]
Hi there,

I get Microsoft.ProjectOxford.Vision.ClientException when i try to run this code. I have verified my keys I am using with the service. 

Below is the stack trace,
Initializing Services
Creating Synonym Map
Create the index
Boosting Documents
Sending a test image through the pipeline
02/23/2018 17:37:03 Info Processing blob:photo_jpg
Processing resized-image
Processing ocr-result
An Error has occured: System.AggregateException: One or more errors occurred. ---> Microsoft.ProjectOxford.Vision.ClientException: Exception of type 'Microsoft.ProjectOxford.Vision.ClientException' was thrown.
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.HandleException(Exception exception)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>b__39_1[TRequest,TResponse](Exception e)
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>d__39`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<RecognizeTextAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.Vision.<GetText>d__7.MoveNext() in C:\Users\meranjit\Downloads\AzureSearch_JFK_Files-master\AzureSearch_JFK_Files-master\Microsoft.Cognitive.Skills\Vision.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.SkillSet`1.<>c__DisplayClass12_0`2.<<AddSkill>b__0>d.MoveNext() in C:\Users\meranjit\Downloads\AzureSearch_JFK_Files-master\AzureSearch_JFK_Files-master\Microsoft.Cognitive.Skills\SkillSet.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.Skill`1.<GetAsync>d__6.MoveNext() in C:\Users\meranjit\Downloads\AzureSearch_JFK_Files-master\AzureSearch_JFK_Files-master\Microsoft.Cognitive.Skills\Skill.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Cognitive.Skills.SkillSet`1.<ApplyAsync>d__5.MoveNext() in C:\Users\meranjit\Downloads\AzureSearch_JFK_Files-master\AzureSearch_JFK_Files-master\Microsoft.Cognitive.Skills\SkillSet.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EnricherFunction.EnrichFunction.<ProcessDocument>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EnricherFunction.EnrichFunction.<Run>d__19.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at DataEnricher.Program.InitializeServices() in C:\Users\meranjit\Downloads\AzureSearch_JFK_Files-master\AzureSearch_JFK_Files-master\DataEnricher\Program.cs:line 158
   at DataEnricher.Program.Main(String[] args) in C:\Users\meranjit\Downloads\AzureSearch_JFK_Files-master\AzureSearch_JFK_Files-master\DataEnricher\Program.cs:line 30
---> (Inner Exception #0) Microsoft.ProjectOxford.Vision.ClientException: Exception of type 'Microsoft.ProjectOxford.Vision.ClientException' was thrown.
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.HandleException(Exception exception)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>b__39_1[TRequest,TResponse](Exception e)
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>d__39`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<RecognizeTextAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.Vision.<GetText>d__7.MoveNext() in C:\Users\meranjit\Downloads\AzureSearch_JFK_Files-master\AzureSearch_JFK_Files-master\Microsoft.Cognitive.Skills\Vision.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.SkillSet`1.<>c__DisplayClass12_0`2.<<AddSkill>b__0>d.MoveNext() in C:\Users\meranjit\Downloads\AzureSearch_JFK_Files-master\AzureSearch_JFK_Files-master\Microsoft.Cognitive.Skills\SkillSet.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.Skill`1.<GetAsync>d__6.MoveNext() in C:\Users\meranjit\Downloads\AzureSearch_JFK_Files-master\AzureSearch_JFK_Files-master\Microsoft.Cognitive.Skills\Skill.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Cognitive.Skills.SkillSet`1.<ApplyAsync>d__5.MoveNext() in C:\Users\meranjit\Downloads\AzureSearch_JFK_Files-master\AzureSearch_JFK_Files-master\Microsoft.Cognitive.Skills\SkillSet.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EnricherFunction.EnrichFunction.<ProcessDocument>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EnricherFunction.EnrichFunction.<Run>d__19.MoveNext()<---

Done.
Press enter to exit

Also i noticed this error does not come if i upload a single page document at a time.

Thanks,
Mercy

**Comment by rajendra747** [comment]
Did u find any solution regarding this i am facing same issue as well.

Thanks & Regards
Rajendra Singh
