### ISSUE TITLE
Error when running Microsoft.Azure.WebJobs.Script.ScriptHost

### ISSUE THREAD

**Issue by mifung** [Microsoft/AzureSearch_JFK_Files#40]
System.IO.FileNotFoundException
  HResult=0x80070002
  ****Message=Could not find file 'D:\All Clients\MARS\Cognitive Search Demo\AzureSearch_JFK_Files-master\AzureSearch_JFK_Files-master\JfkWebApiSkills\JfkWebApiSkills\bin\Debug\netstandard2.0\bin\function.json'.****
  Source=System.Private.CoreLib
  StackTrace:
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.Azure.WebJobs.Script.ScriptHost.ReadFunctionMetadata(String scriptDir, ILogger logger, Dictionary`2 functionErrors, ScriptSettingsManager settingsManager, IEnumerable`1 functionWhitelist) in C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs:line 1081

**Comment by mifung** [comment]
I found the function.json file in multiple locations

**Comment by mifung** [comment]
I can see the function.json in the subfolders such as facet-graph-nodes, hocr-generator, inage-store and link-cryptonyms,
but not at the …\netstandard2\bin\ location.
