### ISSUE TITLE
EntityLinking key error

### ISSUE THREAD

**Issue by nadia-karch** [Microsoft/AzureSearch_JFK_Files#6]
Got stuck in ‘Update code’ step 5  that states:

_Set DataEnricher is as the default project and hit F5 to run it. It should run without errors and create the search indexes, blob containers, and test your settings. If it fails check your settings to ensure they are correct._

I get the follwin error when I run this by hitting F5.

Initializing Services
Creating Synonym Map
Create the index
Boosting Documents
Sending a test image through the pipeline
03/06/2018 09:24:04 Info Processing blob:photo_jpg
Processing resized-image
Processing ocr-result
Processing ocr-handwriting
Processing computer-vision
Processing linked-entities
An Error has occured: System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Access Denied).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.ProjectOxford.EntityLinking.EntityLinkingServiceClient.<SendRequestAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.EntityLinking.EntityLinkingServiceClient.<LinkAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.SkillSet`1.<>c__DisplayClass14_0`4.<<AddSkill>b__0>d.MoveNext() in C:\Users\nakarch\AzureSearch_JFK_Files\Microsoft.Cognitive.Skills\SkillSet.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.Skill`1.<GetAsync>d__6.MoveNext() in C:\Users\nakarch\AzureSearch_JFK_Files\Microsoft.Cognitive.Skills\Skill.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Cognitive.Skills.SkillSet`1.<ApplyAsync>d__5.MoveNext() in C:\Users\nakarch\AzureSearch_JFK_Files\Microsoft.Cognitive.Skills\SkillSet.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EnricherFunction.EnrichFunction.<ProcessDocument>d__22.MoveNext() in C:\Users\nakarch\AzureSearch_JFK_Files\EnricherFunction\EnrichFunction.cs:line 353
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EnricherFunction.EnrichFunction.<Run>d__21.MoveNext() in C:\Users\nakarch\AzureSearch_JFK_Files\EnricherFunction\EnrichFunction.cs:line 336
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at DataEnricher.Program.InitializeServices() in C:\Users\nakarch\AzureSearch_JFK_Files\DataEnricher\Program.cs:line 158
   at DataEnricher.Program.Main(String[] args) in C:\Users\nakarch\AzureSearch_JFK_Files\DataEnricher\Program.cs:line 30
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Access Denied).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.ProjectOxford.EntityLinking.EntityLinkingServiceClient.<SendRequestAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ProjectOxford.EntityLinking.EntityLinkingServiceClient.<LinkAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.SkillSet`1.<>c__DisplayClass14_0`4.<<AddSkill>b__0>d.MoveNext() in C:\Users\nakarch\AzureSearch_JFK_Files\Microsoft.Cognitive.Skills\SkillSet.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Cognitive.Skills.Skill`1.<GetAsync>d__6.MoveNext() in C:\Users\nakarch\AzureSearch_JFK_Files\Microsoft.Cognitive.Skills\Skill.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Cognitive.Skills.SkillSet`1.<ApplyAsync>d__5.MoveNext() in C:\Users\nakarch\AzureSearch_JFK_Files\Microsoft.Cognitive.Skills\SkillSet.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EnricherFunction.EnrichFunction.<ProcessDocument>d__22.MoveNext() in C:\Users\nakarch\AzureSearch_JFK_Files\EnricherFunction\EnrichFunction.cs:line 353
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EnricherFunction.EnrichFunction.<Run>d__21.MoveNext() in C:\Users\nakarch\AzureSearch_JFK_Files\EnricherFunction\EnrichFunction.cs:line 336<---

Done.
Press enter to exit

Resolution: 
there has been a recent change in the way API keys for the Entity Linking Service are handled.  This service is being deprecated and the functionality moved to the Text Analytics Service.  Need to wait for code update that supports the new Text Analytics Service

**Comment by mvdpavan** [comment]
For the above issue, we can fix the issue by just changing the EntitylinkingServiceClient overload method and pass another variable "Apiroot" in "EnrichFunction.cs" under EnrichFunction project. at line:40. Below is the code for refernce.
 static EnrichFunction()
        {
            blobContainer = new ImageStore($"DefaultEndpointsProtocol=https;AccountName={Config.IMAGE_AZURE_STORAGE_ACCOUNT_NAME};AccountKey={Config.IMAGE_BLOB_STORAGE_ACCOUNT_KEY};EndpointSuffix=core.windows.net", Config.IMAGE_BLOB_STORAGE_CONTAINER);
            visionClient = new Vision(Config.VISION_API_KEY, Config.VISION_API_REGION);
            var serviceClient = new SearchServiceClient(Config.AZURE_SEARCH_SERVICE_NAME, new SearchCredentials(Config.AZURE_SEARCH_ADMIN_KEY));
            indexClient = serviceClient.Indexes.GetClient(Config.AZURE_SEARCH_INDEX_NAME);
            linkedEntityClient = new EntityLinkingServiceClient(Config.ENTITY_LINKING_API_KEY, "https://api.labs.cognitive.microsoft.com");
            cosmosDb = new AnnotationStore();

            // read the list of cia-cryptonymns
            using (Stream stream = Assembly.GetExecutingAssembly().GetManifestResourceStream("EnricherFunction.cia-cryptonyms.json"))
            using (StreamReader reader = new StreamReader(stream))
            {
                cryptonymns = JsonConvert.DeserializeObject<Dictionary<string,string>>(reader.ReadToEnd());
            }
        }

**Comment by Careyjmac** [comment]
I am closing this issue as this is from the old version of the JFK Files demo and appears to have been resolved.
