### ISSUE TITLE
npm run start:dev error errno 4294967295

### ISSUE THREAD

**Issue by csotomon** [microsoft/AzureSearch_JFK_Files#79]
When a call the `npm run start:dev` command i get this error:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start:dev' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prestart:dev', 'start:dev', 'poststart:dev' ]
5 info lifecycle jfk-files@1.0.0 prestart:dev: jfk-files@1.0.0
6 info lifecycle jfk-files@1.0.0 start:dev: jfk-files@1.0.0
7 verbose lifecycle jfk-files@1.0.0 start:dev: unsafe-perm in lifecycle true
8 verbose lifecycle jfk-files@1.0.0 start:dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\descomp\tirso-idata\frontend\node_modules\.bin;C:\Program Files\ImageMagick-7.0.8-Q16;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Python\Python37\Scripts\;C:\Python\Python37\;C:\Users\CamiloSoto\AppData\Local\Microsoft\WindowsApps;C:\Users\CamiloSoto\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\CamiloSoto\AppData\Roaming\npm;C:\Users\CamiloSoto\AppData\Local\Programs\Azure Data Studio\bin;C:\poppler\bin;C:\Users\CamiloSoto\.dotnet\tools;C:\Program Files\Microsoft Office\root\Client
9 verbose lifecycle jfk-files@1.0.0 start:dev: CWD: C:\descomp\tirso-idata\frontend
10 silly lifecycle jfk-files@1.0.0 start:dev: Args: [ '/d /s /c',
10 silly lifecycle   'env-cmd .env cross-env NODE_ENV=development webpack-dev-server --config=webpack.dev.config.js' ]
11 silly lifecycle jfk-files@1.0.0 start:dev: Returned: code: 4294967295  signal: null
12 info lifecycle jfk-files@1.0.0 start:dev: Failed to exec start:dev script
13 verbose stack Error: jfk-files@1.0.0 start:dev: `env-cmd .env cross-env NODE_ENV=development webpack-dev-server --config=webpack.dev.config.js`
13 verbose stack Exit status 4294967295
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid jfk-files@1.0.0
15 verbose cwd C:\descomp\tirso-idata\frontend
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start:dev"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 4294967295
22 error jfk-files@1.0.0 start:dev: `env-cmd .env cross-env NODE_ENV=development webpack-dev-server --config=webpack.dev.config.js`
22 error Exit status 4294967295
23 error Failed at the jfk-files@1.0.0 start:dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 4294967295, true ]

But if i call `npm run start:prod` all is OK

**Comment by nohanaga** [comment]
@csotomon 
It didn't work in my environment either, but it worked fine with `webpack-dev-server@2.9.4`.

**Comment by Careyjmac** [comment]
Closing due to inactivity
